import {AuthError,COOKIE} from './auth.mjs';
export function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});}
export function tokenFrom(request){const raw=request.headers.get('cookie')||'';return raw.split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);}
export function getOrigin(){const origin=process.env.APP_ORIGIN;if(!origin)throw Error('APP_ORIGIN is required');const url=new URL(origin);if(url.origin!==origin)throw Error('APP_ORIGIN must be an origin without trailing slash');const local=process.env.ALLOW_HTTP_LOCALHOST==='true'&&['localhost','127.0.0.1'].includes(url.hostname);if(process.env.NODE_ENV==='production'&&url.protocol!=='https:'&&!local)throw Error('Production requires HTTPS');return origin;}
export function assertOrigin(request){if(request.headers.get('origin')!==getOrigin())throw new AuthError(403,'Запрос с другого сайта запрещён.');}
export async function body(request){if(!request.headers.get('content-type')?.startsWith('application/json'))throw new AuthError(415,'Ожидается JSON.');const reader=request.body?.getReader();if(!reader)throw new AuthError(400,'Пустой запрос.');let size=0;const chunks=[];try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>4096){await reader.cancel();throw new AuthError(413,'Слишком большой запрос.');}chunks.push(Buffer.from(value));}const value=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!value||Array.isArray(value)||typeof value!=='object')throw Error();return value;}catch(error){if(error instanceof AuthError)throw error;throw new AuthError(400,'Некорректный JSON.');}}
export function sessionCookie(token,expires){const secure=getOrigin().startsWith('https:');return `${COOKIE}=${token}; Path=/; HttpOnly; SameSite=Strict; Expires=${expires.toUTCString()}${secure?'; Secure':''}`;}
export function clearCookie(){return sessionCookie('',new Date(0))+'; Max-Age=0';}
export async function guarded(fn){try{return await fn();}catch(error){if(error instanceof AuthError)return json({error:error.message},error.status,error.status===429?{'Retry-After':'900'}:{});console.error('Auth request failed:',error.code||error.name);return json({error:'Сервис входа временно недоступен. Проверьте подключение сервера к базе данных.'},503);}}
