(function(){
  'use strict';
  const M=window.AkimModel, root=document.getElementById('akim-planner'), q=s=>root.querySelector(s);
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>n.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2});
  const sign=n=>(n>=0?'+':'')+fmt(n), storageKey='akim-app-v2:'+window.AKIM_USER_ID;
  let history=[{id:1,sheets:M.seed(),plan:[]}],current=history[0],selected=[0,0],view='plan',sheet='Районы',pending=false,issues=[],readToken=0;
  let storageAvailable=true;
  try{const stored=JSON.parse(localStorage.getItem(storageKey));if(stored){if(!Array.isArray(stored.history)||!stored.history.length||stored.history.length>10)throw Error();stored.history.forEach(h=>{if(!Number.isInteger(h.id)||!Array.isArray(h.plan)||!M.evaluate(h.sheets,h.plan).withinLimits)throw Error();});if(new Set(stored.history.map(h=>h.id)).size!==stored.history.length)throw Error();history=stored.history;current=history.find(h=>h.id===stored.current)||history[0];}}catch{storageAvailable=false;}
  let draft=M.clone(current.sheets);
  function save(){try{localStorage.setItem(storageKey,JSON.stringify({history,current:current.id}));storageAvailable=true;}catch{storageAvailable=false;}q('#ap-save-state').textContent=storageAvailable?'Сценарий сохранён в этом браузере':'Сохранение недоступно — скачайте сценарий';}
  function selection(){const m=current.sheets.Мероприятия[selected[0]], d=m.Охват==='Город'?'*':current.sheets.Районы[selected[1]].Район;return {measure:m.Мероприятие,district:d};}
  const same=(a,b)=>a.measure===b.measure&&a.district===b.district;
  function setChoice(enabled){const choice=selection(),plan=current.plan.filter(p=>!same(p,choice));if(enabled)plan.push(choice);const next=M.evaluate(current.sheets,plan);if(!next.withinLimits){q('#ap-error').hidden=false;q('#ap-error').textContent=next.violations[0]||'План нарушает ограничения. Уберите мероприятие и попробуйте снова.';return;}current.plan=plan;q('#ap-error').hidden=true;render();save();}
  function render(){
    const s=current.sheets,x=M.evaluate(s,current.plan),a=x.after,b=x.before,ds=s.Районы,ms=s.Мероприятия;
    q('#ap-spent').textContent=fmt(x.spent);q('#ap-limit').textContent='Лимит бюджета: '+fmt(x.budget)+' усл. ед.';q('#ap-remaining').textContent='Остаток: '+fmt(x.budget-x.spent);q('#ap-budgetbar').style.width=Math.min(100,x.spent/x.budget*100)+'%';
    q('#ap-score').textContent=fmt(a.score);q('#ap-base').textContent=fmt(b.score);q('#ap-gain').textContent=sign(a.score-b.score);q('#ap-count').textContent=x.count+' / '+x.required;
    q('#ap-coverage').textContent='Охват: '+x.coverage.length+' из '+ds.length+' районов';q('#ap-district-count').textContent='РАЙОНОВ: '+ds.length;
    q('#ap-plan-status').textContent=x.valid?'План готов к оценке':('Предпросмотр · выберите ещё '+(x.required-x.count)+' решений');
    q('#ap-plan thead').innerHTML='<tr><th scope="col">Мероприятие</th>'+ds.map(d=>'<th scope="col">'+esc(d.Район)+'</th>').join('')+'</tr>';
    let html='';
    M.categories.forEach(cat=>{html+='<tr class="ap-category"><td colspan="'+(ds.length+1)+'">'+esc(cat)+'</td></tr>';ms.forEach((m,i)=>{if(m.Направление!==cat)return;html+='<tr><td>'+esc(m.Мероприятие)+'<div class="ap-price">'+fmt(M.num(m.Стоимость))+' ед. · лаг '+m.Лаг+' кв. · '+(m.Охват==='Город'?'весь город':'один район')+'</div></td>';const targets=m.Охват==='Город'?['*']:ds.map(d=>d.Район);targets.forEach((d,j)=>{const active=current.plan.some(p=>same(p,{measure:m.Мероприятие,district:d}));html+='<td'+(d==='*'?' colspan="'+ds.length+'"':'')+'><button class="ap-cell '+(active?'ap-funded':'')+'" data-action="'+i+'" data-district="'+j+'" aria-pressed="'+(selected[0]===i&&(d==='*'||selected[1]===j))+'" aria-label="'+esc(m.Мероприятие+', '+(d==='*'?'весь город':d))+'">'+(active?'✓ В плане':'Выбрать')+(d==='*'?'<span>Одна мера для всех районов</span>':'')+'</button></td>';});html+='</tr>';});});q('#ap-rows').innerHTML=html;
    const c=selection(),m=ms[selected[0]],active=current.plan.some(p=>same(p,c)),factor=(8-M.num(m.Лаг))/8;
    q('#ap-selected-name').textContent=m.Мероприятие;q('#ap-selected-district').textContent=c.district==='*'?'Все районы · оплачивается один раз':c.district+' район';q('#ap-selected-cost').textContent=fmt(M.num(m.Стоимость))+' усл. ед.';q('#ap-selected-effect').textContent=fmt(factor*100)+'% полного эффекта';
    const effect=s.Эффекты.find(e=>e.Мероприятие===c.measure&&e.Район===ds[selected[1]].Район);
    q('#ap-selected-category').innerHTML='Горизонт: 8 кварталов. Задержка: '+m.Лаг+' кв.<br>'+M.keys.map((k,i)=>M.num(effect[k])?esc(k+' · '+M.labels[i])+': '+sign(M.num(effect[k])*factor):'').filter(Boolean).join('<br>')+(c.district==='*'?'<br>Показаны эффекты для района «'+esc(ds[selected[1]].Район)+'». Все районные значения — на вкладке данных.':'');
    root.querySelectorAll('[data-level]').forEach(btn=>btn.setAttribute('aria-pressed',String((btn.dataset.level==='1')===active)));
    const weak=ds[a.district.indexOf(a.worst)].Район;
    q('#ap-advice').innerHTML='<p><strong>'+esc(weak)+' — самый слабый район</strong><br>Индекс: '+fmt(a.worst)+'.</p><p>Изменение городского балла: '+sign(a.score-b.score)+'.<br>Критических показателей: '+a.critical+' (было '+b.critical+').</p><p>Активных синергий по районам: '+x.activeSynergies.length+'.</p><p>Разбор составлен по результатам расчёта, без генеративного ИИ.</p>';
    q('#ap-districts').innerHTML=ds.map((d,i)=>'<section class="ap-box"><h2>'+esc(d.Район)+'</h2><p class="ap-small ap-muted">Доля населения: '+fmt(a.shares[i]*100)+'%</p><div class="ap-big">'+fmt(a.district[i])+' <span class="ap-unit">'+sign(a.district[i]-b.district[i])+'</span></div><div class="ap-track"><div class="ap-fill" style="width:'+a.district[i]+'%"></div></div><p class="ap-small ap-muted">До: '+fmt(b.district[i])+'</p><div class="ap-indicators">'+M.keys.map((k,j)=>'<div class="ap-pair"><span title="'+esc(M.labels[j])+'">'+k+' · '+esc(M.labels[j])+'</span><strong class="'+(x.values[i][j]<40?'ap-critical':'')+'">'+fmt(x.base[i][j])+' → '+fmt(x.values[i][j])+'</strong></div>').join('')+'</div></section>').join('');
    q('#ap-metrics').innerHTML=M.categories.map((cat,i)=>{const k=i*2,w=M.weights[k]+M.weights[k+1];const value=v=>v.reduce((sum,row,d)=>sum+a.shares[d]*(row[k]*M.weights[k]+row[k+1]*M.weights[k+1])/w,0);return '<div class="ap-result-row"><div class="ap-pair"><span>'+cat+'</span><span>'+fmt(value(x.base))+' → '+fmt(value(x.values))+'</span></div><div class="ap-track"><div class="ap-fill" style="width:'+value(x.values)+'%"></div></div></div>';}).join('');
    q('#ap-breakdown').innerHTML='<h2>Из чего складывается балл</h2><div class="ap-equation">0,7 × '+fmt(a.average)+' + 0,3 × '+fmt(a.worst)+' − '+a.critical+' = '+fmt(a.raw)+'</div><p>После ограничения 0–100: <strong>'+fmt(a.score)+'</strong></p><p class="ap-small ap-muted">Числа показаны с округлением; расчёт использует полную точность.</p><div class="ap-separator"></div><p>Вклад изменения среднего: '+sign(.7*(a.average-b.average))+'; худшего района: '+sign(.3*(a.worst-b.worst))+'; штрафов: '+sign(b.critical-a.critical)+'. Поправка ограничения шкалы: '+sign((a.score-a.raw)-(b.score-b.raw))+'.</p><h3 style="margin-top:16px">Синергии</h3>'+(x.activeSynergies.length?x.activeSynergies.map(v=>'<p class="ap-small">'+esc(v.first+' + '+v.second+' · '+v.district)+': '+v.delta.map((v,i)=>v?M.keys[i]+' '+sign(v):'').filter(Boolean).join(', ')+'</p>').join(''):'<p class="ap-small ap-muted">Нет активных пар.</p>');
    q('#ap-plan').hidden=view!=='plan';q('#ap-results').hidden=view!=='results';q('.ap-workspace').hidden=view==='data';q('#ap-data').hidden=view!=='data';['plan','result','data'].forEach(n=>q('#ap-'+n+'-tab').setAttribute('aria-pressed',String(view===(n==='result'?'results':n))));
    q('#ap-current').textContent='Версия '+current.id+' · '+s.Настройки[0]['Название набора'];q('#ap-versions').innerHTML=history.map(h=>'<option value="'+h.id+'" '+(h===current?'selected':'')+'>Версия '+h.id+' · '+esc(h.sheets.Настройки[0]['Название набора'])+'</option>').join('');
  }
  function status(message,error=false){q('#ap-import-status').textContent=message;q('#ap-import-status').dataset.error=String(error);}
  function preview(){const data=draft[sheet]||[];q('#ap-import-head').innerHTML='<tr>'+M.headers[sheet].map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr>';q('#ap-import-body').innerHTML=data.slice(0,100).map(r=>'<tr>'+M.headers[sheet].map(h=>'<td>'+esc(r[h]??'—')+'</td>').join('')+'</tr>').join('');q('#ap-import-count').textContent='Строк: '+data.length;q('#ap-import-help').textContent='Показаны первые '+Math.min(100,data.length)+' строк. '+({Районы:'Показатели 0–100; доли населения должны в сумме давать 1.',Мероприятия:'Охват: Район или Город. Лаг: 0–8 кварталов. Одна мера выбирается один раз.',Эффекты:'Все пары мероприятие × район обязательны. Отрицательные эффекты допустимы.',Синергии:'Мера 1 и 2 задаются кодами M1–M14. Район * — каждый подходящий район; бонус не зависит от лага.',Ограничения:'Правило «везде» запрещает пару в любом районе; «в одном районе» — только в одном и том же.',Настройки:'Бюджет и число решений. Для кейса: 100 условных единиц и ровно 5 мер.'}[sheet]);root.querySelectorAll('[data-sheet]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.sheet===sheet)));q('#ap-check-districts').textContent=draft.Районы?.length||0;q('#ap-check-actions').textContent=draft.Мероприятия?.length||0;q('#ap-check-errors').textContent=issues.length;q('#ap-apply').disabled=!pending||issues.length>0||!q('#ap-confirm').checked;if(issues.length){q('#ap-import-status').innerHTML='<strong>Исправьте ошибки</strong><ul>'+issues.slice(0,8).map(e=>'<li>'+esc(e)+'</li>').join('')+'</ul><p>Всего ошибок: '+issues.length+'</p>';q('#ap-import-status').dataset.error='true';}}
  let importedPlan=[];
  function stage(s,label,plan=[]){issues=M.validate(s);if(!issues.length){try{if(!Array.isArray(plan)||!M.evaluate(s,plan).withinLimits)throw Error('План превышает ограничения.');}catch(e){issues.push(e.message);}}if(Object.keys(M.headers).some(k=>!Array.isArray(s?.[k]))){pending=false;status(issues.join(' '),true);q('#ap-apply').disabled=true;return;}draft=s;importedPlan=plan;pending=true;q('#ap-confirm').checked=false;status(label+' · '+(issues.length?'Найдены ошибки.':'Данные проверены, но ещё не применены.'));preview();}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const jsonDownload=(value,name)=>download(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),name);
  let library;
  function excel(){if(window.XLSX)return Promise.resolve(window.XLSX);if(library)return library;library=new Promise((resolve,reject)=>{const tag=document.createElement('script');tag.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';tag.onload=()=>{if(window.XLSX)resolve(window.XLSX);else{library=null;reject(Error('Модуль Excel недоступен. Используйте JSON или CSV.'));}};tag.onerror=()=>{library=null;reject(Error('Для Excel нужен интернет. JSON и CSV работают без сети.'));};document.head.appendChild(tag);});return library;}
  function parseCSV(text){text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0],delimiter=first.includes(';')?';':',',rows=[];let row=[],value='',inside=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(inside&&text[i+1]==='"'){value+='"';i++;}else inside=!inside;}else if(c===delimiter&&!inside){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!inside){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(v=>v.trim()))rows.push(row);row=[];value='';}else value+=c;}if(inside)throw Error('CSV: незакрытые кавычки.');row.push(value);if(row.some(v=>v.trim()))rows.push(row);return rows;}
  function fromRows(key,rows){const h=(rows.shift()||[]).map(v=>String(v).trim());if(new Set(h).size!==h.length||M.headers[key].some(k=>!h.includes(k)))throw Error('Лист «'+key+'»: неверные заголовки.');return rows.filter(r=>r.some(v=>String(v??'').trim())).map(r=>Object.fromEntries(M.headers[key].map(k=>[k,typeof r[h.indexOf(k)]==='string'?r[h.indexOf(k)].trim():r[h.indexOf(k)]??''])));}
  root.querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>{sheet=b.dataset.sheet;preview();});q('#ap-confirm').onchange=preview;
  q('#ap-demo').onclick=()=>{readToken++;stage(M.seed(),'Демонстрационный набор');};
  q('#ap-json-template').onclick=()=>jsonDownload(M.seed(),'akim-data.json');
  q('#ap-template').onclick=async()=>{try{const X=await excel(),book=X.utils.book_new();Object.keys(M.headers).forEach(k=>X.utils.book_append_sheet(book,X.utils.aoa_to_sheet([M.headers[k],...draft[k].map(r=>M.headers[k].map(h=>r[h]))]),k));download(new Blob([X.write(book,{bookType:'xlsx',type:'array'})]),'akim-data.xlsx');}catch(e){status(e.message,true);}};
  q('#ap-csv-template').onclick=()=>{const quote=v=>'"'+String(v).replace(/"/g,'""')+'"';download(new Blob(['\uFEFF'+[M.headers[sheet],...draft[sheet].map(r=>M.headers[sheet].map(h=>r[h]))].map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),sheet+'.csv');};
  q('#ap-upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;const token=++readToken;pending=false;q('#ap-confirm').checked=false;q('#ap-apply').disabled=true;status('Чтение файла…');try{if(file.size>1024*1024)throw Error('Файл больше 1 МБ.');let s,plan=[];if(/\.json$/i.test(file.name)){const value=JSON.parse(await file.text());s=value.sheets||value;plan=value.plan||[];}else if(/\.csv$/i.test(file.name)){const rows=parseCSV(await file.text()),h=rows[0]||[],key=Object.keys(M.headers).find(k=>M.headers[k].every(v=>h.includes(v)));if(!key)throw Error('Не удалось определить лист CSV.');s=M.clone(draft);s[key]=fromRows(key,rows);sheet=key;}else if(/\.xlsx$/i.test(file.name)){const X=await excel(),book=X.read(await file.arrayBuffer(),{type:'array',sheetRows:2003});s={};for(const k of Object.keys(M.headers)){const ws=book.Sheets[k];if(!ws)throw Error('Нет листа «'+k+'».');if(ws['!fullref']&&X.utils.decode_range(ws['!fullref']).e.r>2000)throw Error('Слишком много строк.');s[k]=fromRows(k,X.utils.sheet_to_json(ws,{header:1,defval:''}));}}else throw Error('Поддерживаются JSON, CSV и XLSX.');if(token===readToken)stage(s,file.name,plan);}catch(err){if(token===readToken){issues=[err.message];pending=false;status(err.message,true);preview();}}e.target.value='';};
  q('#ap-apply').onclick=()=>{if(!pending||issues.length||!q('#ap-confirm').checked)return;readToken++;current={id:Math.max(...history.map(h=>h.id))+1,sheets:M.clone(draft),plan:M.clone(importedPlan)};history.push(current);if(history.length>10)history.shift();selected=[0,0];pending=false;q('#ap-confirm').checked=false;status('Данные применены. Предыдущие сценарии доступны в списке версий.');render();preview();save();};
  q('#ap-versions').onchange=e=>{readToken++;current=history.find(h=>h.id===+e.target.value);selected=[0,0];draft=M.clone(current.sheets);pending=false;issues=[];q('#ap-confirm').checked=false;status('Открыта версия '+current.id);render();preview();save();};
  q('#ap-rows').onclick=e=>{const b=e.target.closest('[data-action]');if(b){selected=[+b.dataset.action,+b.dataset.district];q('#ap-error').hidden=true;render();if(window.innerWidth<=950)q('#ap-selected-name').parentElement.scrollIntoView({block:'start',behavior:'smooth'});}};
  q('#ap-levels').onclick=e=>{const b=e.target.closest('[data-level]');if(b)setChoice(b.dataset.level==='1');};
  q('#ap-plan-tab').onclick=()=>{view='plan';render();};q('#ap-result-tab').onclick=()=>{view='results';render();};q('#ap-data-tab').onclick=()=>{view='data';render();preview();};
  q('#ap-analyze').onclick=()=>{const x=M.evaluate(current.sheets,current.plan);if(!x.valid){view='plan';render();q('#ap-error').hidden=false;q('#ap-error').textContent=x.violations[0]||(x.count!==x.required?'Выберите ровно '+x.required+' мероприятия.':'План не прошёл проверку.');q('#ap-plan-status').textContent='План не завершён: '+x.count+' / '+x.required+' решений';return;}view='results';render();q('#ap-plan-status').textContent='Итоговая оценка готова · горизонт 8 кварталов';};
  q('#ap-export').onclick=()=>jsonDownload({format:'akim-scenario-v2',sheets:current.sheets,plan:current.plan,result:M.evaluate(current.sheets,current.plan)},'akim-scenario.json');
  let undo=[],undoVersion=null;q('#ap-reset').onclick=()=>{undo=M.clone(current.plan);undoVersion=current.id;current.plan=[];q('#ap-undo').hidden=!undo.length;q('#ap-error').hidden=true;render();save();};q('#ap-undo').onclick=()=>{if(undoVersion!==current.id){q('#ap-undo').hidden=true;return;}const restored=M.evaluate(current.sheets,undo);if(!restored.withinLimits)return;current.plan=undo;q('#ap-undo').hidden=true;render();save();};
  render();preview();save();
})();
