'use client';
import {useEffect,useState} from 'react';
export default function Home(){
  const [user,setUser]=useState(null),[loading,setLoading]=useState(true),[mode,setMode]=useState('login'),[registration,setRegistration]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[show,setShow]=useState(false),[login,setLogin]=useState('');
  async function refresh(){try{const r=await fetch('/api/me',{cache:'no-store'});if(r.ok){setUser((await r.json()).user);setError('');}else if(r.status===401){setUser(null);}else{setUser(null);setError('Сервис входа недоступен. Повторите попытку позже.');}}catch{setUser(null);setError('Нет связи с сервером.');}finally{setLoading(false);}}
  useEffect(()=>{refresh();fetch('/api/auth/config').then(r=>r.json()).then(x=>setRegistration(x.registration)).catch(()=>{});},[]);
  useEffect(()=>{if(!user)return;const id=setInterval(refresh,60000),onFocus=()=>{if(document.visibilityState==='visible')refresh();};document.addEventListener('visibilitychange',onFocus);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',onFocus);};},[user?.id]);
  async function submit(event){event.preventDefault();setError('');setNotice('');const data=new FormData(event.currentTarget);if(mode==='register'&&data.get('password')!==data.get('confirm')){setError('Пароли не совпадают.');return;}setBusy(true);try{const response=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:data.get('login'),password:data.get('password'),name:data.get('name')})});const result=await response.json();if(!response.ok)throw Error(result.error||'Не удалось выполнить запрос.');if(mode==='register'){setMode('login');setNotice('Аккаунт создан. Войдите с вашим логином и паролем.');}else{setUser(result.user);setNotice('');}}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function logout(){setBusy(true);setError('');try{const r=await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'}});if(!r.ok)throw Error('Не удалось завершить сессию. Повторите попытку.');setUser(null);setMode('login');setNotice('Вы вышли из аккаунта.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  if(loading)return <main className="loading" role="status">Проверяем сессию…</main>;
  if(user)return <main className="workspace"><header className="account"><div className="brand"><span className="logo">А</span><strong>АКИМ</strong><span className="muted">Личный кабинет</span></div><div className="identity"><div><strong>{user.name}</strong><small>@{user.login} · {user.role==='admin'?'Организатор':'Участник'}</small></div><button onClick={logout} disabled={busy}>{busy?'Выходим…':'Выйти'}</button></div></header>{error&&<div className="error" role="alert">{error}</div>}<iframe key={user.id} src="/simulator" title="Симулятор городского бюджета" className="simulator"/><footer className="account-note">Вход и сессия проверяются сервером. Планы пока сохраняются локально, отдельно для каждого аккаунта.</footer></main>;
  return <main className="auth-shell"><section className="intro"><div className="brand"><span className="logo">А</span><strong>АКИМ</strong><span>городская лаборатория</span></div><div><div className="eyebrow">Аким на 5 часов</div><h1>Город начинается<br/>с решений.</h1><p>Войдите в свой аккаунт, чтобы работать с бюджетом города и сравнивать результаты ваших решений.</p><div className="intro-facts"><span>5 направлений</span><span>Один бюджет</span><span>Ваш сценарий</span></div></div><small>Учебная модель управления городом</small></section><section className="form-area"><div className="login-card"><div className="eyebrow">Городская лаборатория</div><h2>{mode==='login'?'С возвращением':'Создайте аккаунт'}</h2><p className="muted">{mode==='login'?'Войдите, чтобы продолжить работу.':'Новый аккаунт получает роль участника.'}</p>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}<form key={mode} onSubmit={submit}>{mode==='register'&&<label>Ваше имя<input name="name" autoComplete="name" maxLength={80} required disabled={busy}/></label>}<label>Логин<input name="login" value={login} onChange={e=>setLogin(e.target.value)} autoComplete="username" pattern="[A-Za-z0-9_.\-]{3,40}" minLength={3} maxLength={40} spellCheck={false} autoCapitalize="none" required disabled={busy} placeholder="Например, city.planner"/></label><label>Пароль<div className="password"><input name="password" type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='register'?12:1} maxLength={128} required disabled={busy}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Скрыть пароль':'Показать пароль'}>{show?'Скрыть':'Показать'}</button></div></label>{mode==='register'&&<><small className="muted">От 12 до 128 символов. Можно использовать длинную фразу.</small><label>Повторите пароль<input name="confirm" type={show?'text':'password'} autoComplete="new-password" required maxLength={128} disabled={busy}/></label></>}<button className="primary" type="submit" disabled={busy}>{busy?'Подождите…':mode==='login'?'Войти в лабораторию':'Создать аккаунт'}</button></form>{registration&&<p className="switch">{mode==='login'?'Ещё нет аккаунта?':'Уже есть аккаунт?'} <button disabled={busy} onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setNotice('');setShow(false);}}>{mode==='login'?'Зарегистрироваться':'Войти'}</button></p>}{!registration&&<p className="muted help">Учётную запись выдаёт организатор.</p>}</div></section></main>;
}
